dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="django<1.11"
  - DJANGO="django<2.0"
  - DJANGO="django<2.1"
  - DJANGO="django<2.2"
  - DJANGO="django<2.3"
  - DJANGO="django<3.1"
  - DJANGO="django<3.2"
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - cd example/ && ./manage.py test testapp --settings=testapp.settings

matrix:
  exclude:
    - python: 2.7
      env: DJANGO="django<2.1"
    - python: 2.7
      env: DJANGO="django<2.2"
    - python: 2.7
      env: DJANGO="django<2.3"
    - python: 2.7
      env: DJANGO="django<3.1"
    - python: 2.7
      env: DJANGO="django<3.2"
    - python: 2.7
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: 3.4
      env: DJANGO="django<2.3"
    - python: 3.4
      env: DJANGO="django<3.1"
    - python: 3.4
      env: DJANGO="django<3.2"
    - python: 3.4
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: 3.5
      env: DJANGO="django<3.1"
    - python: 3.5
      env: DJANGO="django<3.2"
    - python: 3.5
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: 3.8
      env: DJANGO="django<1.11"
    - python: 3.8
      env: DJANGO="django<2.0"
    - python: 3.8
      env: DJANGO="django<2.1"
  allow_failures:
     - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
