dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  - DJANGO="django<2.3"
  - DJANGO="django<3.1"
  - DJANGO="django<3.2"
  - DJANGO="django<3.3"
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - cd example/ && ./manage.py test testapp --settings=testapp.settings

matrix:
  allow_failures:
     - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  exclude:
    - python: 3.9
      env: DJANGO="django<2.3"
